Document: createrepo-c
Title: Debian createrepo-c Manual
Author: <insert document author here>
Abstract: This manual describes what createrepo-c is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/createrepo-c/createrepo-c.sgml.gz

Format: postscript
Files: /usr/share/doc/createrepo-c/createrepo-c.ps.gz

Format: text
Files: /usr/share/doc/createrepo-c/createrepo-c.text.gz

Format: HTML
Index: /usr/share/doc/createrepo-c/html/index.html
Files: /usr/share/doc/createrepo-c/html/*.html
